###
GET http://localhost:8080/api/auth/getUser
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImE4YmZhNzU2NDk4ZmRjNTZlNmVmODQ4YWY5NTI5ZThiZWZkZDM3NDUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc3ByaW5nLWJvb3QtYXV0aGVudGljYXRpb24iLCJhdWQiOiJzcHJpbmctYm9vdC1hdXRoZW50aWNhdGlvbiIsImF1dGhfdGltZSI6MTY2MTQ0NDk2MywidXNlcl9pZCI6Im51OUhDSnBmM0VZWllNVlV4VE9rVjdGTGw4MTIiLCJzdWIiOiJudTlIQ0pwZjNFWVpZTVZVeFRPa1Y3RkxsODEyIiwiaWF0IjoxNjYxNDQ0OTYzLCJleHAiOjE2NjE0NDg1NjMsImVtYWlsIjoidGVzdDVAbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsidGVzdDVAbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.awerst4GtIJHSM7oLCoHeyyEOY0Dr03qroj-o3z0OdLwimYdSV0DRsilJ4i2n7UxkDZ3sMygs3UqpME4TzfR8pl4GOekiyPt8KZ6ERWI70aPLCKqLvh0kpUCefLYq8xI68f3KbEpowK7lM8cpAzI9XdkC2Ixh2r1jt-efPp5OYziGlRWNjcDfYsQO6nOL1eZJXOnGy5epB6S4-eys2sMKE1lYZUIM5HyQzbRSmh-Is22QqXGGgcZ5cy6YnQs36rx_QwxciKkEIHNcANRXGia6_fPWKOlX7OzjrqkomQcrjLydZNSxes2dHVhYOIwaCTyBEsrAvuAR_cPIThH72nKhA
